project_name: erp
before:
  hooks:
    - go mod tidy
dist: release
source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Tag }}-source'
checksum:
  name_template: '{{ .ProjectName }}-{{ .Tag }}-checksums.txt'
builds:
- id: erpctl
  env:
  - CGO_ENABLED=0
  main: ./cmd/client/main.go
  binary: erpctl
  ldflags:
  - -s -w
  - -X "github.com/bhojpur/erp/pkg/version.Version={{.Version}}-{{.ShortCommit}}"
  - -X "github.com/bhojpur/erp/pkg/version.BuildTime={{ time "2006-01-02 15:04:05 MST" }}"
  - -X "github.com/bhojpur/erp/pkg/version.BuildCommit={{ .FullCommit }}"
- id: erpsvr
  env:
  - CGO_ENABLED=0
  main: ./cmd/server/main.go
  binary: erpsvr
  ldflags:
  - -s -w
  - -X "github.com/bhojpur/erp/pkg/version.Version={{.Version}}-{{.ShortCommit}}"
  - -X "github.com/bhojpur/erp/pkg/version.BuildTime={{ time "2006-01-02 15:04:05 MST" }}"
  - -X "github.com/bhojpur/erp/pkg/version.BuildCommit={{ .FullCommit }}"
archives:
- id: erpctl
  files:
  - "none*"
  format: binary # this removes the tar of the archives, leaving the binaries alone
  name_template: erpctl-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
  replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
  builds:
  - erpctl
- id: erpsvr
  files:
  - "none*"
  format: binary # this removes the tar of the archives, leaving the binaries alone
  name_template: erpsvr-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
  builds:
  - erpsvr
  replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  prerelease: auto
  header: |
    Bhojpur ERP is a high performance enterprise resource planning system driving many distributed applications
    and services running over the Bhojpur.NET Platform.
dockers:
  - goos: linux
    goarch: amd64
    goarm: ''
    dockerfile: Dockerfile
    image_templates:
    - "ghcr.io/bhojpur/erp:{{ .Tag }}"
    extra_files:
    - README.md